name: 'Test Report Assembler'
description: 'Assemble test reports from multiple sources'

inputs:
  test_reports:
    description: 'the folder containing the test reports'
    required: true
    default: 'test-reports'
  
  output_file:
    description: 'the file to write the assembled test report to'
    required: true
    default: 'assembled-test-report.json'

runs:
  # setup python 3.11 environment, install dependencies
  - name: Setup Python 3.11
    uses: actions/setup-python@v2
    with:
      python-version: '3.11'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  # run the script
  - name: Assemble test reports
    run: python main.py ${{ inputs.test_reports }} ${{ inputs.output_file }}