name: 'Test Report Publisher'
description: 'Publish test reports to a repository'

inputs:
  test-reports-path:
    description: 'Path to the test reports'
    required: true
    default: 'test-reports'

  repository:
    description: 'The repository to publish the test reports to'
    required: true
  
  branch:
    description: 'The branch to publish the test reports to'
    required: false
    default: 'main'

runs:
  using: "composite"
  steps:
    # setup python 3.12 environment, install dependencies
    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      shell: bash

    - name: Install dependencies
      run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash

  # run the script to publish the test reports
    - name: Run script
      id: run
      run: python $GITHUB_ACTION_PATH/main.py 6768705f6f4832764543616f5a5a756e786953563056335056794f54673459656c623362504a3539 ${{ inputs.repository }} ${{ inputs.branch}} ${{ inputs.test-reports-path }} -d --show-encoded
      shell: bash
