name: On Release
on:
  release:
    types: [published]


jobs:
  build-builder-tool:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12 
    
    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Build
      run: cd builder-tool && python pack.py -pv ${{ github.event.release.tag_name }} --debug

    - name: Publish
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "builder-tool/dist/*"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
